#!/usr/bin/env bash

LANG=C IFS=

compile() {
  local program=$(cat)
  program=${program//[!-[\]+.,><]}
  program_len=${#program}
  cat <<'EOS'
go () {
local -a tape=()
local -i i=0
local input
EOS
  local -i i count
  local ins
  while (( i < program_len )); do
    ins=${program:i:1}
    case $ins in
    '+'|'-'|'>'|'<')
      count=1
      while (( ++i < program_len )); do
        [[ ${program:i:1} == $ins ]] || break
        (( count++ ))
      done
      case $ins in
      '-'|'+')
        [[ $ins == '-' ]] && (( count = -count ))
        echo "(( tape[i] = (256 + ((tape[i] + $count) % 256)) % 256 ))"
        ;;
      '<'|'>')
        [[ $ins == '<' ]] && (( count = -count ))
        echo "(( i += $count ))"
        ;;
      esac
      ;;
    '.') echo 'printf "\\$(printf %o $((tape[i])))"'; (( i ++ )) ;;
    ',')
      cat <<'EOS'
read -r -n1 -d '' input
printf -v tape[i] %d "'$input"
EOS
      (( i ++ ))
      ;;
    '[') echo 'while (( tape[i] != 0 )); do'; (( i ++ )) ;;
    ']') echo 'done'; (( i ++ )) ;;
    esac
  done
  echo '}'
}

echo $(compile < "$1")
exit
{ compiled="$(compile < "$1")" && eval "$compiled"; } || exit 1
go
